version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin_password@postgres:5432/progress_db"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: progress_db
    ports:
       - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_user@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
